[firebase]
apiKey = "AIzaSyB6pf3fiwI1ssAaUrPEZ-vomI8uJ90xVmc"
authDomain = "habit-tracker-aede3.firebaseapp.com"
projectId = "habit-tracker-aede3"
storageBucket = "habit-tracker-aede3.firebasestorage.app"
messagingSenderId = "389808817558"
appId = "1:389808817558:web:cfa00daab26fb7e4ec49b7"
measurementId = "G-530CPQVWBD"

[service_account]
type = "service_account"
project_id = "habit-tracker-aede3"
private_key_id = "7035accb4b3f4c471ef70c7aeec5622fe0a10cb1"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC76LDCUwJN46rI\nrv55BhaLRswx5RRZNpuJZB1QXCO7YzRoNmAumh9rxMSsYEIv6ThfO5LGrZhQPd2M\npMZgCwXybIVQYBlqaGsMLaN+nELczlWH+PoCpgXZ5/I9UYQEaAuLhG8Ayu8DERYp\n16IGarXei/IFDlf9dJLonhyaHvrtb9hbuSXZ3odNGkGRlHGgdTr9JDx7XcRnwyUO\nB17rI8KhO7ouvtNA3aCR4gSKpOyFaiLXTrTt7/lAxAunK7SXNTua/BfKOB2f06oQ\nSqKdz1RIbJVJYc1Uy7xVF53mrCUFshGaJgyZwVfb7NbsX0UE1Kk4h1xc0Eq4z8qs\n8U7UK79/AgMBAAECggEABtXVp8BkQHSFJUHJq5nkl7XVogUAguC2egWrjN1lKj1z\no0zRSL7o0ngjgOULRRZV5Fa4Qif/2o2Z/+r92I5sUTwJOvoU0NGVqfB3SG4/t7oo\nKKqq0X/04qR76u4YxzqzOUEq8vgLQEJAd6P1OkEVWjOtHs1oRTQIiD5yXAO/e0r6\n4f/WPgMS+htxw2hdNm664UKU6/pdxkcmxuMTWkdfYR4Jt/Los5l5KB7L6PTIZR/D\nfE295fvuayqHaFIYHWjQFi4lOALiXNiK3aTPerg+ieRRqnkEnV5YRWfaHy05rQpv\n4v6YOuir7VTucKmYXlsyV2MDhEYf1mZxn4JOXnDFfQKBgQDkL8Z44SCy3BLBS4hT\nNfCOLhhKbO8mMDdZfpx+GRE0aGVz4u7A07YoXYtVGhmRAsuriHCRKdJP68ns+dPy\nheSZsPLPxcxtnq/FmbRk2NfII5vje13iWa/gVtPEux+hE4HrFjBBwz5cpahLs0TU\ngfAK7rv32W7QzYsIjuWvoI098wKBgQDS0BwyIJ/9a1WbltQ3yvA0nDQ2mneRyuRs\nd3TmIL/mWbYwp0wPy2bOIFWPe7vEr508u/bk5c+xRJm4zwgdeEZxeOxGOoUMxbmF\n0Cmyk8XFRRyUamDF0GFAOmlK/T2XXz/Umx2UB4gTaj7RONlTNNQ7mTEE4sDdLQwp\n8iT6VUf/RQKBgDmtDbh+BtrOn3r2EYYeyyfU5NTjBeucIlFfnESPJ3ccsBADmx9o\nI9G+GzqudyndEAfSW8mFTaBf09EvMHBLgYWLYUQ9FbfbdUg32o3m9VukDIIKK6fL\nzZWhvLMsLQl0udDm8dmddQTL5mcD7/DaywaoYyB5d/YVDgBixhGHPkwbAoGBAJn6\nH14Nrk3vI+ws0nyd4azLmud3E3aNdyIyblPX/9JEHGqVB11R95j+zP+sJI2Yp4RA\n1iiCIp0buhveO9Mqkmk3JXx2KdAWa1dtn8crX/yiaimNOXnCpgW/pEB9j4sMqxai\n5YvFpIJpy9ANcc7we0O8tK0Y4j2qNYQ9tPyTZa7xAoGAdRMNC4nr+gXjrqsThpvQ\nB6FNMLPVHzH/HYBMKsQVf4S5kUqEh3CRRMMdkNVuaYDZNDtOGXT1FRts1yS8DFcb\njHsmDR9RKj/Tpwkt+o513oAhcJ854BqDzxYhq9bajvalmcyPkpCSRTEgDaPcnLYe\nLnkr6/cD+TxKZtv/MDxj/U8=\n-----END PRIVATE KEY-----\n"
client_email = "firebase-adminsdk-fbsvc@habit-tracker-aede3.iam.gserviceaccount.com"
client_id = "115172762111603172744"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40habit-tracker-aede3.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[app]
user_count = 10
